# NixOS Configuration - Main Entry Point
# This is the main configuration file that imports all modules

{ config, pkgs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix
    
    # Centralized configuration
    ./modules/config.nix
    
    # Core modules
    ./modules/core/boot.nix
    ./modules/core/network.nix
    ./modules/core/nix.nix
    ./modules/core/system.nix
    
    # Locale module
    ./modules/locale
    
    # Hardware modules
    ./modules/hardware/gpu/amd.nix
    ./modules/hardware/gpu/nvidia.nix
    ./modules/hardware/gpu/intel.nix
    ./modules/hardware/audio.nix
    ./modules/hardware/bluetooth.nix
    ./modules/hardware/printing.nix
    
    # Graphics modules
    ./modules/graphics/wayland.nix
    ./modules/graphics/xorg.nix
    
    # Desktop modules
    ./modules/desktop/plasma.nix
    ./modules/desktop/gnome.nix
    ./modules/desktop/cosmic.nix
    ./modules/desktop/xfce.nix
    ./modules/desktop/mate.nix
    ./modules/desktop/hyprland.nix
    ./modules/desktop/i3.nix
    ./modules/desktop/awesome.nix
    
    # Services modules
    ./modules/services/docker.nix
    ./modules/services/ollama.nix
    ./modules/services/ssh.nix
    # ./modules/services/lsyncd.nix  # User-specific, see .old/lsyncd.nix
    
    # Storage modules
    ./modules/storage/lvm.nix
    ./modules/storage/zfs.nix
    # ./modules/storage/volumes.nix  # User-specific, see .old/volumes.nix
    
    # Users module
    ./modules/users/default.nix
    ./modules/users/groups.nix
    
    # System packages
    ./modules/packages.nix
    
    # Profile (optional, uncomment one)
    # ./profiles/minimal.nix
    # ./profiles/desktop.nix
    # ./profiles/server.nix
    # ./profiles/developer.nix
  ];

  # Essential system packages
  environment.systemPackages = with pkgs; [
    vim
    wget
    curl
    git
    htop
    tree
    unzip
    zip
  ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken.
  # Don't change this unless you know what you're doing!
  system.stateVersion = "24.11";
}
